### ISSUE TITLE
[Feature Request] tracker by git branch

### ISSUE THREAD

**Issue by Bajdzis** [JanBN/vscode-time-tracker-and-reminder#1]
Hi!
I'm very appreciate your extension. I need count time by project and current branch in git.  Could you add this features? What do you think?

**Comment by JanBN** [comment]
Try it now. There is new setting - trackGitBranch, by default it is turned off.
`"time-tracker.trackGitBranch": false`

**Comment by Bajdzis** [comment]
Thanks ! 😃
